$script_mysql = <<-SCRIPT
    apt-get update && \
    apt-get install -y mysql-server-5.7 && \
    mysql -e "create user 'phpuser'@'%' identified by 'pass';"
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"

    config.vm.define "mysqldb" do |mysqldb|
        #mysqldb.vm.network "private_network", ip: "192.168.50.4"
        #mysqldb.vm.network "private_network", type: "dhcp"
        #mysqldb.vm.network "public_network"
        mysqldb.vm.network "public_network", ip: "192.168.3.250"


        mysqldb.vm.synced_folder "./configs", "/configs"
        mysqldb.vm.synced_folder ".", "/vagrant", disabled: true

        mysqldb.vm.provision "shell", inline: "echo Hello, World >> hello.txt"

        mysqldb.vm.provision "shell", inline: $script_mysql

        mysqldb.vm.provision "shell", 
            inline: "cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"


        mysqldb.vm.provision "shell", 
            inline: "service mysql restart"


    end
        
    config.vm.define "phpweb" do |phpweb|
        phpweb.vm.network "forwarded_port", guest: 80, host: 8082
        phpweb.vm.network "public_network", ip: "192.168.3.251"
    end
    
end