$script_mysql = <<-SCRIPT
    apt-get update && \
    apt-get install -y mysql-server-5.7 && \
    mysql -e "create user 'phpuser'@'%' identified by 'pass';"
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.provider "virtualbox" do |vbox|
        vbox.memory = 512
        vbox.cpus = 1
    end
      

    #config.vm.define "mysqldb" do |mysqldb|
        #mysqldb.vm.network "private_network", ip: "192.168.50.4"
        #mysqldb.vm.network "private_network", type: "dhcp"
        #mysqldb.vm.network "public_network"
        #mysqldb.vm.network "public_network", ip: "192.168.3.250"


        #mysqldb.vm.synced_folder "./configs", "/configs"
        #mysqldb.vm.synced_folder ".", "/vagrant", disabled: true

        #mysqldb.vm.provision "shell", inline: "echo Hello, World >> hello.txt"

        #mysqldb.vm.provision "shell", inline: $script_mysql

        #mysqldb.vm.provision "shell", 
        #    inline: "cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"


        #mysqldb.vm.provision "shell", 
        #    inline: "service mysql restart"


    #end
        

    config.vm.define "mysqlserver" do |mysqlserver|
        mysqlserver.vm.network "public_network", ip: "192.168.3.250"
        mysqlserver.vm.provision "shell",
        inline: "cat /vagrant/configs/id_bionic.pub >> .ssh/authorized_keys"

    end

    config.vm.define "ansible" do |ansible|
        ansible.vm.network "public_network", ip: "192.168.3.252"
        ansible.vm.provision "shell",
        inline: "apt-get update && \
                     apt-get upgrade -y && \
                     apt-get install -y software-properties-common && \
                     apt-add-repository --yes --update ppa:ansible/ansible && \
                     apt-get install -y ansible"

        ansible.vm.provision "shell",
            inline: "cp /vagrant/id_bionic /home/vagrant && \
                     chmod 600 /home/vagrant/id_bionic && \
                     chown vagrant:vagrant /home/vagrant/id_bionic"

        ansible.vm.provision "shell",
            inline: "ansible-playbook -i /vagrant/configs/ansible/hosts \
                /vagrant/configs/ansible/playbook.yml"
        

    end

    config.vm.define "phpweb" do |phpweb|
        phpweb.vm.network "forwarded_port", guest: 8888, host: 8082

        phpweb.vm.provider "virtualbox" do |vbox|
            vbox.memory = 1024
            vbox.cpus = 1
            vbox.name = "ubuntu_bionic_php7"
        end

        phpweb.vm.network "public_network", ip: "192.168.3.251"

        phpweb.vm.provision "shell",
            inline: "apt-get update && apt-get install -y puppet"

        phpweb.vm.provision "puppet" do |puppet|
            puppet.manifests_path = "./configs/manifests"
            puppet.manifest_file = "phpweb.pp"
        end
    end
    
    config.vm.define "memcached" do |memcached|
        memcached.vm.box = "centos/7"
        memcached.vm.provider "virtualbox" do |vbox|
            vbox.memory = 1024
            vbox.cpus = 1
            vbox.name = "ubuntu_bionic_memcached"
        end
    end
end